
% memo.m
%
%                  $Id: memo experiment.m 380 2012-12-26 07:00:55Z steeve $
%                usage: mglTestDots(screenNumber,numsec)
%                   by: Steeve Laquitaine
%                 date: 12/11/26
%              Purpose: How is prior's strength represented?
%              Subject: Steeve
% Experiment structure: {2 priors *
%                        3 coherences {0.08(~108 trials), 0.16(72 trials), 0.32(36 trials)} 
%                        for 36 directions}

%      sessions length: 
%       session number: 
%             schedule:
                        % 1) training (S1)
                        % 2) main  (S1)
                        % 3) main  (S2)
                        % the sequence of runs is randomized within subjects and across
                        % subjects (1) 
                           
%               Usage: this code requires 2 files to work properly:
                        % - task.mat files (parameters) contained in a method file: e.g.,
                        % "120925_steeve_exp03_metho_param_dir6_var0030_mean195_coh012_024_062_1_t125_eye.mat"
                        % this file is generated by the function 'initPriors'
                        % - taskDotDir.m (function that run the experiment)

% Procedure
% # the parameters for each sub-block are pre-set with 'initPriors' for
% 70 trials per coherence and stored in the directory in a 'metho'.mat file.    
    

%NOTE: Regime more toward accuracy than speed (low speed/accuracy ratio);
%Because the effects of the prior strengths are subtle particularly with 4
%priors.



% Test new experiment with increased motion speed (to reduce MAE)

% SI [45 min]
taskDotDir('steeve_exp12_metho_Pstd010_mean225_coh006012024_dir36_t107_073_033perCoh_130217')%dropped frames: 0.00 %130217
taskDotDir('steeve_exp12_metho_Pstd080_mean225_coh006012024_dir36_t106_075_034perCoh_130217')%dropped frames: 0.00
taskDotDir('steeve_exp12_metho_Pstd020_mean225_coh006012024_dir36_t107_075_033perCoh_130217')%dropped frames: 0.00
taskDotDir('steeve_exp12_metho_Pstd040_mean225_coh006012024_dir36_t101_075_031perCoh_130217')%dropped frames: 0.00
% optionnally but preferably
taskDotDir('steeve_exp12_metho_Pstd080_mean225_coh006012024_dir36_t106_075_034perCoh_130217')%dropped frames: 0.00
% Note: It reduces MAE



% SII repeat [34 min] - here: 1h30 min
taskDotDir('steeve_exp12_metho_Pstd010_mean225_coh006012024_dir36_t107_073_033perCoh_130217')%dropped frames: 0.00 %130217
taskDotDir('steeve_exp12_metho_Pstd020_mean225_coh006012024_dir36_t107_075_033perCoh_130217')%dropped frames: 0.00
taskDotDir('steeve_exp12_metho_Pstd080_mean225_coh006012024_dir36_t106_075_034perCoh_130217')%dropped frames: 0.00
taskDotDir('steeve_exp12_metho_Pstd040_mean225_coh006012024_dir36_t101_075_031perCoh_130217')%dropped frames: 0.00
% optionnally but preferably
taskDotDir('steeve_exp12_metho_Pstd080_mean225_coh006012024_dir36_t106_075_034perCoh_130217')%dropped frames: 0.00
% Note: It significantly reduces MAE



% SIII repeat [34 min] - here: 2h15 min
taskDotDir('steeve_exp12_metho_Pstd080_mean225_coh006012024_dir36_t106_075_034perCoh_130217')%dropped frames: 0.00 %130217
taskDotDir('steeve_exp12_metho_Pstd010_mean225_coh006012024_dir36_t107_073_033perCoh_130217')%dropped frames: 0.00
taskDotDir('steeve_exp12_metho_Pstd020_mean225_coh006012024_dir36_t107_075_033perCoh_130217')%dropped frames: 0.00
taskDotDir('steeve_exp12_metho_Pstd040_mean225_coh006012024_dir36_t101_075_031perCoh_130217')%dropped frames: 0.00
% optionnally but preferably
taskDotDir('steeve_exp12_metho_Pstd080_mean225_coh006012024_dir36_t106_075_034perCoh_130217')%dropped frames: 0.00



% SIV - repeat [34 min] - here: 2h15 min
taskDotDir('steeve_exp12_metho_Pstd040_mean225_coh006012024_dir36_t101_075_031perCoh_130217')%dropped frames: 0.00 %130503
taskDotDir('steeve_exp12_metho_Pstd080_mean225_coh006012024_dir36_t106_075_034perCoh_130217')%dropped frames: 0.00
taskDotDir('steeve_exp12_metho_Pstd010_mean225_coh006012024_dir36_t107_073_033perCoh_130217')%dropped frames: 0.00
taskDotDir('steeve_exp12_metho_Pstd020_mean225_coh006012024_dir36_t107_075_033perCoh_130217')%dropped frames: 0.00
taskDotDir('steeve_exp12_metho_Pstd080_mean225_coh006012024_dir36_t106_075_034perCoh_130217')%dropped frames: 0.00


% SV -  repeat [45 min] - here: 3h45 min, done
taskDotDir('steeve_exp12_metho_Pstd020_mean225_coh006012024_dir36_t107_075_033perCoh_130217')%dropped frames: 0.00 %130716
taskDotDir('steeve_exp12_metho_Pstd040_mean225_coh006012024_dir36_t101_075_031perCoh_130217')%dropped frames: 0.00 
taskDotDir('steeve_exp12_metho_Pstd010_mean225_coh006012024_dir36_t107_073_033perCoh_130217')%dropped frames: 0.00
taskDotDir('steeve_exp12_metho_Pstd080_mean225_coh006012024_dir36_t106_075_034perCoh_130217')%dropped frames: 0.00
taskDotDir('steeve_exp12_metho_Pstd080_mean225_coh006012024_dir36_t106_075_034perCoh_130217')%dropped frames: 0.00





