      
%       author: steeve laquitaine
%         date: 140425
%      purpose: simulate a matrix bold responses for m voxels and n trials
%      produced by brain areas encoding likelihood, prior and posterior of
%      displayed motion directions.
%        usage: [llhBOLDmn,postBOLDmn,priorBold]=simBayesianBold(dirTrained,...
%     'priorstd=0',...
%     'priormean=225',...
%     'numVoxelsMT=1',...
%     'numVoxelsLIP=100',...
%     'NeurInaVoxelMT=1',...
%     'NeurInaVoxelLIP=1000',...
%     whichNeurInaVoxelMT,...
%     whichNeurInaVoxelLIP,...
%     whichNeurInaVoxelPrior,...
%     15,...
%     'sortVoxels=on',...
%     'displayNetwork=off',... 
%     'displayBOLD=off');
%
 %description: simulate BOLD with direction-tuned neuron in the encoding
 %stage and readout neurons in the decoding stage.

%inspired from Habenschuss paper in Neural Network, 2013

%requires my code library
%addpath(genpath('~/Dropbox/Library/Library_code/matlab/'))

function [llhBOLDmn,postBOLDmn,PriorBOLDmn,k,VoxRespAmpPrior,VoxPrefDirllh,VoxPrefDirPost,whichNeurInaVoxelllh,whichNeurInaVoxelPost,whichNeurInaVoxelPrior]=simBayesianBold(motionDir,...
    priorstd,...
    priormean,...
    numVoxelsMT,...
    numVoxelsLIP,...
    NeurInaVoxelMT,...
    NeurInaVoxelLIP,...
    whichNeurInaVoxelMT,...
    whichNeurInaVoxelLIP,...
    whichNeurInaVoxelPrior,...
    numNeurMTkj,...
    sortVoxels,...
    OptiondisplayNetwork,...
    OptiondisplayBOLD)

%1 Simulate BOLD data "posterior Bold" (m voxels, 
%n trials) from a Bayesian model with multiplicative gain
[llhBOLDmn,postBOLDmn,PriorBOLDmn,k,VoxRespAmpPrior,VoxPrefDirllh,VoxPrefDirPost,whichNeurInaVoxelllh,whichNeurInaVoxelPost,whichNeurInaVoxelPrior]=NNwithXGain2(motionDir,...
    priorstd,...
    priormean,...
    numVoxelsMT,...
    numVoxelsLIP,...
    NeurInaVoxelMT,...
    NeurInaVoxelLIP,...
    whichNeurInaVoxelMT,...
    whichNeurInaVoxelLIP,...
    whichNeurInaVoxelPrior,...
    numNeurMTkj,...
    sortVoxels,...
    OptiondisplayNetwork,...
    OptiondisplayBOLD);
