function checkFitHeuristic

%it works fine (see logBook for all the codes)
%~10% response bias
%(1) best matching(true) parameters
%(2) 8x stronger priors & best matching llh
%(3) 8x weaker priors & best matching llh
%(4) 8x stronger likelihoods & best matching priors
%(5) 8x stronger likelihoods & stronger priors
%(6) 8x stronger likelihoods & weaker priors
%(7) 8x weaker likelihood & true priors
%(8) 8x weaker likelihood & stronger priors
%(9) 8x weaker likelihood & weaker priors
%(10)likelihoods & priors are same.
    %+-----+-------+----------------------+
    %|     |       |          prior       |
    %.-----|-------+-------+-------+------+
    %|     |       | true  | strong| weak |
    %.-----|-------+-------+-------+------+      
    %|     |true   |(1)t-t |(2)t-s |(3)t-w|
    %.     |-------+-------+-------+------+
    %| llh |strong |(4)s-t |(5)s-s |(6)s-w|
    %|     |-------+-------+-------+------+
    %|     |weak   |(7)w-t |(8)w-s |(9)w-w|
    %+-----+-----------------------+------+
load fitfake03
figure('color','w')
ax=plot(logL_bkp,'r.','markersize',30);
xlabel('Initial parameters','fontsize',14)
ylabel('-sum(logL) over trials','fontsize',14)
set(gca,'xtick',1:30,'xticklabel',{'best match',...
    'best llh - 8x prior',...
    'best llh - prior/8',...
    '8xllh - best prior',...
    '8xllh - 8xprior',...
    '8xllh - prior/8',...
    'llh/8 - best prior',...
    'llh/8 - 8xprior',...
    'llh/8 - prior/8',...
    'llh=prior',...
    'best match - respBias50%',...
    'best llh - 8x prior',...
    'best llh - prior/8',...
    '8xllh - best prior',...
    '8xllh - 8xprior',...
    '8xllh - prior/8',...
    'llh/8 - best prior',...
    'llh/8 - 8xprior',...
    'llh/8 - prior/8',...
    'llh=prior',...
    'best match - respBias90%',...
    'best llh - 8x prior',...
    'best llh - prior/8',...
    '8xllh - best prior',...
    '8xllh - 8xprior',...
    '8xllh - prior/8',...
    'llh/8 - best prior',...
    'llh/8 - 8xprior',...
    'llh/8 - prior/8',...
    'llh=prior'})
set(gca,'fontsize',14)
box off
rotateXLabels(gca(),90)