
% memo.m
%
%                  $Id: memo experiment.m 380 2012-12-26 07:00:55Z steeve $
%                   by: Steeve Laquitaine
%                 date: 12/12/20
%              Purpose: Control with random initial position of the mouse
%              Subject: Steeve

%      sessions length: 
%       session number: 
%             schedule:
                        % 1) training (S1)
                        % 2) main  (S1)
                        % 3) main  (S2)
                        % the sequence of runs is randomized within subjects and across
                        % subjects (1) 
                           
%               Usage: this code requires 2 files to work properly:
                        % - task.mat files (parameters) contained in a method file: e.g.,
                        % "120925_steeve_exp03_metho_param_dir6_var0030_mean195_coh012_024_062_1_t125_eye.mat"
                        % this file is generated by the function 'initPriors'
                        % - taskDotDir.m (function that run the experiment)

%Procedure
%# the parameters for each sub-block are pre-set with 'initPriors' for
%stored in the directory in a 'metho'.mat file.    
  
%Information to save the file
saveinfo.datadir='~/Dropbox/Project_withJustin/Code/Code_controlInitPosition/data';
saveinfo.subjectID='sub01';

%SI [45 min]
taskDotDir('steeve_exp12_metho_Pstd010_mean225_coh006012024_dir36_t107_073_033perCoh_130217',saveinfo)%dropped frames: 
taskDotDir('steeve_exp12_metho_Pstd080_mean225_coh006012024_dir36_t106_075_034perCoh_130217',saveinfo)%dropped frames: 
taskDotDir('steeve_exp12_metho_Pstd020_mean225_coh006012024_dir36_t107_075_033perCoh_130217',saveinfo)%dropped frames: 
taskDotDir('steeve_exp12_metho_Pstd040_mean225_coh006012024_dir36_t101_075_031perCoh_130217',saveinfo)%dropped frames: 
taskDotDir('steeve_exp12_metho_Pstd080_mean225_coh006012024_dir36_t106_075_034perCoh_130217',saveinfo)%dropped frames: 

% SII repeat [34 min] - here: 1h30 min
taskDotDir('steeve_exp12_metho_Pstd010_mean225_coh006012024_dir36_t107_073_033perCoh_130217',saveinfo)%dropped frames:  
taskDotDir('steeve_exp12_metho_Pstd020_mean225_coh006012024_dir36_t107_075_033perCoh_130217',saveinfo)%dropped frames: 
taskDotDir('steeve_exp12_metho_Pstd080_mean225_coh006012024_dir36_t106_075_034perCoh_130217',saveinfo)%dropped frames: 
taskDotDir('steeve_exp12_metho_Pstd040_mean225_coh006012024_dir36_t101_075_031perCoh_130217',saveinfo)%dropped frames: 
taskDotDir('steeve_exp12_metho_Pstd080_mean225_coh006012024_dir36_t106_075_034perCoh_130217',saveinfo)%dropped frames: 

% SIII repeat [34 min] - here: 2h15 min
taskDotDir('steeve_exp12_metho_Pstd080_mean225_coh006012024_dir36_t106_075_034perCoh_130217',saveinfo)%dropped frames:  
taskDotDir('steeve_exp12_metho_Pstd010_mean225_coh006012024_dir36_t107_073_033perCoh_130217',saveinfo)%dropped frames: 
taskDotDir('steeve_exp12_metho_Pstd020_mean225_coh006012024_dir36_t107_075_033perCoh_130217',saveinfo)%dropped frames: 
taskDotDir('steeve_exp12_metho_Pstd040_mean225_coh006012024_dir36_t101_075_031perCoh_130217',saveinfo)%dropped frames: 
taskDotDir('steeve_exp12_metho_Pstd080_mean225_coh006012024_dir36_t106_075_034perCoh_130217',saveinfo)%dropped frames: 

% SIV - repeat [34 min] - here: 2h15 min
taskDotDir('steeve_exp12_metho_Pstd040_mean225_coh006012024_dir36_t101_075_031perCoh_130217',saveinfo)%dropped frames:  
taskDotDir('steeve_exp12_metho_Pstd080_mean225_coh006012024_dir36_t106_075_034perCoh_130217',saveinfo)%dropped frames: 
taskDotDir('steeve_exp12_metho_Pstd010_mean225_coh006012024_dir36_t107_073_033perCoh_130217',saveinfo)%dropped frames: 
taskDotDir('steeve_exp12_metho_Pstd020_mean225_coh006012024_dir36_t107_075_033perCoh_130217',saveinfo)%dropped frames: 
taskDotDir('steeve_exp12_metho_Pstd080_mean225_coh006012024_dir36_t106_075_034perCoh_130217',saveinfo)%dropped frames: 

% SV -  repeat [45 min] - here: 3h45 min, done
taskDotDir('steeve_exp12_metho_Pstd020_mean225_coh006012024_dir36_t107_075_033perCoh_130217',saveinfo)%dropped frames:  
taskDotDir('steeve_exp12_metho_Pstd040_mean225_coh006012024_dir36_t101_075_031perCoh_130217',saveinfo)%dropped frames:  
taskDotDir('steeve_exp12_metho_Pstd010_mean225_coh006012024_dir36_t107_073_033perCoh_130217',saveinfo)%dropped frames: 
taskDotDir('steeve_exp12_metho_Pstd080_mean225_coh006012024_dir36_t106_075_034perCoh_130217',saveinfo)%dropped frames: 
taskDotDir('steeve_exp12_metho_Pstd080_mean225_coh006012024_dir36_t106_075_034perCoh_130217',saveinfo)%dropped frames: 





