
%slfmrigetSingleVoxTuningRawPeak.m
%
%
% author: steeve laquitaine
%  date : 160114
% status: completed and tested
%purpose: plot voxel tuning fit over variable 0 (e.g., directions) sorted 
%         by variable 1 (e.g., coherence or switching)
%
%Description: voxel responses are normalized to the mean response ((resp/mean)*100)
%
%  usage:
%
%      st = slfmrigetSingleVoxTuningRawPeak(1,'myRandomDir','mySwitch',15,d,'fminsearch')
%       
%
%input:
%     voxnum : voxel you want to plot (column of d.instances)
%       var0 : tuning x space (e.g., direction, orientation or location)
%       var1 : sort the tunings by other variable "var1" (e.g., coherence, switching)
%       var2 : another variable to select the data (e.g., 'myRandomCoh=0.06')
%          d : contains data in "d.instances" (n repeats x m voxels matrix)
%              variable 0 (e.g.,d.myRandomDir (n repeats x 1 vector)
%              variable 1 (e.g.,d.myRandomCoh (n repeats x 1 vector)
%              d can be generated by "slfmriGetInstancedb.m"
%
%    'nofit' : ("fminsearch", "gridsearchMean", or "cmaes"):
%
%               "gridsearchMean": Use it even if slow. it is very resistant 
%               to local minima. It set von mises initial mean
%               parameters with a grid search 1:1:360, the amplitude to the
%               mean amplitude over directions and k at 4. But slow (10 min/
%               500 voxels with parallel computing). Qualitatively good fit.
%
%               "fminsearch" is very fast 10 sec/500 voxels. But very
%               sensitive to local minima. For example it produces aberrant
%               high frequencies of voxel selectivities at 350 deg for simulation
%               of random values dataset. Qualitatively good fit.
%               
%
%varargin:
%       
%     'color': colors of plot
%              e.g., 'colors',[0 0 1]
%
%output :
%
%         conditions: n examples x m variables matrix of conditions
%     conditionsSubs: # of unique conditions
%       numCondition: # of unique conditions
%              count: 
%               mean: 
%                sem: 
%          fitvmMean: 
%             fitvmK: 
%             fitvmA: the amplitude scaling parameter
%         st.peakAmp: A*exp(k)/(2*pi.*besseli(0,k)); (The peak amplitude)
%      fitvmEquation: 'A*exp(k.*cos(x-u)-k)./(2*pi.*besseli(0,k,1))'
%          st.minsqe: best sum of squared error between model predictions and data
%        st.rsquared: percent explained variance in the data by the model
%
%
%
function st = slfmrigetSingleVoxTuningRawPeak(voxnum,var0,var1,var2,d,fitAlgo,varargin)

o = getAnalysisParams(varargin{:});

%case tuning is sorted by var1 values
%====================================
if ~any(var1=='=')
    
    %Bold response (instances by voxels)
    y = d.instances;
    
    %tuning x space
    x0 = d.(var0);

    %other variable to sort tuning
    x1 = d.(var1);
    
    %other variable to sort tuning
    var2nm = var2(1:find(var2=='=')-1);
    var2val = str2double(var2(find(var2=='=')+1:end));       
    x2 = d.(var2nm);
    
    %scale data to % signal change to the mean
    percSignal = d.instances(:,voxnum)/mean(d.instances(:,voxnum),1)*100;
    
    %Bold response (instances by voxels) for variable 1 value
    y = percSignal;
    
    %get stats (instance mean and sem by condition)
    st = SLmakeStat(y,x0,x1,x2);
    
    %unique variable values
    x1u = unique(x1);
    
    %plot mean and sem each condition
    set(gcf,'color','w')
    mycolx1 = linspecer(length(x1u));
    
    %tuning by var1 and var2 condition (colors)
    h = nan(1,length(x1u));
    lg = num2cell(h);
    for ix1 = 1 : length(x1u)
        var1Val = x1u(ix1);
        posVars = st.conditions(:,2) == var1Val & st.conditions(:,3) == var2val;
        var0Val = st.conditions(posVars,1);
        hold all
        %when condition exists
        if any(posVars)
            myerrorbar(var0Val,st.mean(posVars),'yError',st.sem(posVars),...
                'Symbol=o',['Color=[' num2str(mycolx1(ix1,:)) ']']);
            %get legend
            h(ix1) = plot(var0Val,st.mean(posVars),'color',mycolx1(ix1,:));
            lg{ix1} = num2str(x1u(ix1));
        end
    end
    xlabel(var0)
    ylabel('Response')
    legend(h,lg)%x1u)
end

%case tuning is for a specific value of var1 (e.g., var1=1)
if any(var1=='=')
    fprintf('%s \n','(slfmrigetVoxTuning) Getting tuning for a specific condition (var1).')
    
    %other variable to get tuning for
    %variable 1 name
    var1nm = var1(1:find(var1=='=')-1);        
    x1all = d.(var1nm);
    
    %var1 values (e.g.,'mySwitch=1') to get tuning for
    var1val = str2double(var1(find(var1=='=')+1:end));
    
    %var2
    var2nm = var2(1:find(var2=='=')-1);
    x2all = d.(var2nm);
    var2val = str2double(var2(find(var2=='=')+1:end));
       
    %tests coherence fixed -------
    posv1val = find((x1all==var1val & x2all==var2val));
    %------------      
    
    %scale data to % signal change to the mean
    percSignal = d.instances(:,voxnum)/mean(d.instances(:,voxnum),1)*100;
    
    %Bold response (instances by voxels) for variable 1 value
    y = percSignal(posv1val);
    
    %variable 0 (e.g., motion directions) for variable 1 value
    x0 = d.(var0)(posv1val);    
    
    %x1 values (same)
    x1 = x1all(posv1val);
    
    %get stats (instance mean and sem) for 
    %variable 1 value
    st = SLmakeStat(y,x0);
        
    %---------- plot mean and sem each condition data -----
    var0Val = st.conditions(:,1);    
    myerrorbar(var0Val,st.mean,'yError',st.sem,...
        'Symbol=o',['Color=' num2str(o.color)]);
    %get legend
    h(1) = plot(var0Val,st.mean,'.','linestyle','none','color',o.color);
    xlabel(var0)
    ylabel('Response')      
            
    %output voxel tuning params
    [A,pos] = max(st.mean);
    st.fitvmMode = var0Val(pos);
    st.fitvmMean = nan;
    st.fitvmK = nan;
    st.fitvmA = A;
    st.peakAmp = A;
    st.fitvmEquation = 'direction that elicits maximum average bold response';
    st.minsqe = nan;
    st.rsquared = nan;
end

function o = getAnalysisParams(varargin)

%color
if any(strcmp(varargin,'color'))
    o.color = varargin{find(strcmp(varargin,'color'))+1};
else
    o.color = 'k';
end

