
%slfitLearningBayes.m
%
%
%
%    author: steeve laquitaine
%     date:
%   purpose: Maximum likelihood fit with all parameters free for a single
%            set of initial parameters
%
%nested functions : slgetloglLearningBayesianModel


function [fitPtmp,negLogl,exitflag,outputFit,fithistory] = slfitLearningBayesSingleParamSet(initp,data,disp,StimStrength,...
    pstd,priorModes,trials,TheModel,options,varargin)

global history
options.OutputFcn = slrecordfit;

%Nelder-Mead
[fitPtmp,negLogl,exitflag,outputFit] = fminsearch(@(fitPtmp) ...
    slgetloglLearningBayesianModel(data,...
    disp,...
    StimStrength,...
    pstd,...
    fitPtmp,...
    priorModes,...
    trials,...
    TheModel),...
    initp,...
    options);

fithistory = history;
